$CC $CPPFLAGS $CFLAGS $LDFLAGS cat.c -o cat
$CC $CPPFLAGS $CFLAGS $LDFLAGS mkdir.c -o mkdir
$CC $CPPFLAGS $CFLAGS $LDFLAGS tr.c -o tr
$CC $CPPFLAGS $CFLAGS $LDFLAGS chmod.c -o chmod
$CC $CPPFLAGS $CFLAGS $LDFLAGS echo.c -o echo
$CC $CPPFLAGS $CFLAGS $LDFLAGS dirname.c -o dirname
$CC $CPPFLAGS $CFLAGS $LDFLAGS which.c -o which
$CC $CPPFLAGS $CFLAGS $LDFLAGS rm.c -o rm
$CC $CPPFLAGS $CFLAGS $LDFLAGS test.c -o test
